language: node_js

node_js:
  - "node"
  - "lts/*"
  - "10"

before_script:
  - npm --version
  - npm install -g @angular/cli
  - ng --version
  ###https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json
  - npm ci -C ./home-ng/
  - git diff

script:
  - make -C ./home-ng/ test build
  - make -C ./home-ng/ pre-release
