language: node_js

node_js:
  - "node"
  - "lts/*"
  - "10"

install:
  - npm --version
  - npm install -g @angular/cli
  - ng --version

script:
  - make -C ./home-ng/ test build
  - make TARGET_FOLDER="/tmp/hongkailiu.github.io-${TRAVIS_JOB_NUMBER}" -C ./home-ng/ pre-release

notifications:
  slack:
    secure: Cv2a3dDmvU42/teK+jdfzMTtQJH/VLgIDXoFpvnEY3rSKerZkPcP/8xomRtBPauG7pqLFFie2X2qiPPlzpiFGFUgJnBp5i5uy03Q/X/ofrOrHsCrMSZ5gxYfcWdDuI4ELyFW/yzr4AcNfTYS6gHtrkxhO0tPo1MG623Vp7cBmCKJRqeaZ4SKZ/QS75IEpGqvikdiv9EWIFzOPGYiI5dlMj8jtdsDafaJhrFdzaWfP7MWnwx92gAbkppe1zJAMHAZZWiOr37iI4z6hxIcjQpifmQCdYXukYZmSBag8RzKodRgi3wm720YmpXjtSV9w+U6uFZbSpP1w+BULqxNRBS0ODYoE3y4Cvot/HMQBeGs5zjRbjxweHN2zRB0yx4fl5KHmGDxJD9uASCiXDTj1o9KBKeMtJjTbeavVzuOVwKVA8OWcyLHEYNGyT1yIyuPqRZL+UB2fL1J3QtUc6KCbz/e4kX5Ro4AD9EnVCqDZIVZ/MbtYAhQWSvYYSJUliqbvIV8/2VZuS2jL4T7CXwL0e6qiZVAk26PexD3HyKQlPdtZHOBDNGw0qFy2zAn058gzBNQsRij4PH57gAt6Yq8OJG9qQNR4VBoko5t1ljsKcEZR+x6qumnmxQUsXDAGcpFSR99L3SgGyxnOzNGNxAoAErvC9RKbzNkgBZTaUwUfoWKj94=
