---
version: 2
jobs:
  build-node-10:
    working_directory: ~/my-project
    docker:
      ###https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node/images
      - image: circleci/node:10.15.1-jessie
    steps:
      - checkout
      - run:
          name: circle-ci-all
          command: "make CIRCLECI=${CIRCLECI} -C ./home-ng/ circle-ci-all"
  build-node-11:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:11.10.0-stretch
    steps:
      - checkout
      - run:
          name: circle-ci-all
          command: "make CIRCLECI=${CIRCLECI} -C ./home-ng/ circle-ci-all"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-node-10
      - build-node-11
