---
version: 2
jobs:
  build-node-13:
    working_directory: ~/my-project
    docker:
      ###https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node/images
      - image: circleci/node:13.11.0-buster
    steps:
      - checkout
      - run:
          name: circle-ci-all
          ###https://stackoverflow.com/questions/56355499/stop-angular-cli-asking-for-collecting-analytics-when-i-use-ng-build
          command: "make CIRCLECI=${CIRCLECI} NG_CLI_ANALYTICS=ci TARGET_FOLDER=/tmp/hongkailiu.github.io-${CIRCLE_BUILD_NUM} -C ./home-ng/ circle-ci-all"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-node-13
