---
version: 2
jobs:
  build-node-13:
    working_directory: ~/my-project
    docker:
      ###https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node/images
      - image: circleci/node:13.11.0-buster
    steps:
      - checkout
      - run:
          name: circle-ci-all
          command: "make CIRCLECI=${CIRCLECI} TARGET_FOLDER=/tmp/hongkailiu.github.io-${CIRCLE_BUILD_NUM} -C ./home-ng/ circle-ci-all"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-node-13
